// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: video_service.proto

#include "video_service.pb.h"
#include "video_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace video {

static const char* VideoService_method_names[] = {
  "/video.VideoService/SendFrame",
};

std::unique_ptr< VideoService::Stub> VideoService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VideoService::Stub> stub(new VideoService::Stub(channel, options));
  return stub;
}

VideoService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendFrame_(VideoService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VideoService::Stub::SendFrame(::grpc::ClientContext* context, const ::video::Frame& request, ::video::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::video::Frame, ::video::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendFrame_, context, request, response);
}

void VideoService::Stub::async::SendFrame(::grpc::ClientContext* context, const ::video::Frame* request, ::video::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::video::Frame, ::video::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendFrame_, context, request, response, std::move(f));
}

void VideoService::Stub::async::SendFrame(::grpc::ClientContext* context, const ::video::Frame* request, ::video::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendFrame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::video::Empty>* VideoService::Stub::PrepareAsyncSendFrameRaw(::grpc::ClientContext* context, const ::video::Frame& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::video::Empty, ::video::Frame, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendFrame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::video::Empty>* VideoService::Stub::AsyncSendFrameRaw(::grpc::ClientContext* context, const ::video::Frame& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendFrameRaw(context, request, cq);
  result->StartCall();
  return result;
}

VideoService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VideoService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VideoService::Service, ::video::Frame, ::video::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VideoService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::video::Frame* req,
             ::video::Empty* resp) {
               return service->SendFrame(ctx, req, resp);
             }, this)));
}

VideoService::Service::~Service() {
}

::grpc::Status VideoService::Service::SendFrame(::grpc::ServerContext* context, const ::video::Frame* request, ::video::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace video

